apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

bases:
- ../../base

replicas:
- name: devops-app
  count: 3

images:
- name: devops-app
  newName: ghcr.io/toolikheng/devops-app
  newTag: latest

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
