apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-app-data
  namespace: devops
  labels:
    app: devops-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
