apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops

bases:
- ../../base

replicas:
- name: devops-app
  count: 1

images:
- name: devops-app
  newName: devops-app
  newTag: latest

patchesStrategicMerge:
- deployment-patch.yaml
